name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Choose the Node.js version your project requires
          cache: "npm" # or 'yarn' if you use Yarn

      - name: Install dependencies
        run: npm ci # or 'yarn install --frozen-lockfile'

      - name: Build
        run: npm run build # or your specific build command

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: ethan-nielsen-portfolio # Replace with your Firebase project ID
